# Generated by Django 2.1.5 on 2019-03-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_marketing', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
